/**
 * Generated by @openapi-codegen
 *
 * @version 1.0
 */
export type TimezoneDTO = {
  value: string;
  label: string;
  abbrev: string;
  altName: string;
  offset: number;
};

export type AuthorDTO = {
  /**
   * @example John Doe
   */
  name: string;
  /**
   * @example null
   */
  url: Record<string, any>;
  /**
   * @example null
   */
  avatar: Record<string, any>;
  /**
   * @example null
   */
  email: Record<string, any>;
};

export type AdditionalDetailsDTO = {
  /**
   * @example en-us
   */
  language: Record<string, any>;
  categories: string[];
  authors: AuthorDTO[];
  /**
   * @example null
   */
  copyright: Record<string, any>;
};

export type FeedDTO = {
  /**
   * @example NASA Breaking News
   */
  title: string;
  /**
   * @example A RSS news feed containing the latest NASA news articles and press releases.
   */
  description: string;
  /**
   * @example http://www.nasa.gov/
   */
  homepage: string;
  /**
   * @example https://www.nasa.gov/rss/dyn/breaking_news.rss
   */
  feed_url: string;
  additional_details: AdditionalDetailsDTO;
};

export type ContentDTO = {
  /**
   * @example Example content
   */
  text: string;
  /**
   * @example <p>Example content</p>
   */
  html: string;
};

export type ImageDTO = {
  /**
   * @example https://www.nasa.gov/sites/default/files/styles/full_width/public/thumbnails/image/iss066e077280_0.jpg
   */
  url: string;
  /**
   * @example 985
   */
  width: number;
  /**
   * @example 657
   */
  height: number;
};

export type NewEntryDTO = {
  /**
   * @example NASA Astronauts to Call Indiana, Texas, Virginia Students from Space
   */
  title: string;
  /**
   * @example http://www.nasa.gov/press-release/nasa-astronauts-to-call-indiana-texas-virginia-students-from-space
   */
  link: string;
  /**
   * @example Students across the country will have three opportunities to hear from NASA astronauts aboard the International Space Station.
   */
  description: string;
  content: ContentDTO;
  /**
   * @example http://www.nasa.gov/press-release/nasa-astronauts-to-call-indiana-texas-virginia-students-from-space
   */
  guid: string;
  image: ImageDTO;
  additional_details: AdditionalDetailsDTO;
  /**
   * @example Fri, 04 Feb 2022 20:13:00 +0000
   */
  time: string;
  /**
   * @example 1644005580
   */
  timestamp: number;
};

export type WebhookDataDTO = {
  /**
   * @example rssapi.net
   */
  webhook_from: string;
  /**
   * @example new entries in feed
   */
  webhook_reason: string;
  /**
   * @example 2
   */
  new_entries_count: number;
  /**
   * @example 22798
   */
  subscription_id: number;
  /**
   * @example 200
   */
  last_webhook_response: number;
  /**
   * @example false
   */
  is_retry: boolean;
  /**
   * @example Your subscription info
   */
  info: string;
  feed: FeedDTO;
  new_entries: NewEntryDTO[];
};

export type ValidateRssFeedDTO = {
  valid_feed: boolean;
  feed_type: string;
};

export type AvailableDTO = {
  available: boolean;
};

export type RegisterTokenEntity = {
  id: string;
  samplePermission: "admin" | "manager" | "editor" | "viewer";
  firmPermission: "admin" | "manager" | "editor" | "viewer";
  email: string;
  firmId: string;
  /**
   * @format date-time
   */
  createdAt: string;
};

export type RegistrationBody = {
  tokenId: string;
  firstName: string;
  lastName: string;
  password: string;
  passwordConfirm: string;
  timezone: string;
};

export type SuccessDTO = {
  success: boolean;
};

export type TokenIdBody = {
  tokenId: string;
};

export type TokenIdPasswordBody = {
  password: string;
  passwordConfirm: string;
  tokenId: string;
};

export type EmailBody = {
  email: string;
};

export type SignupEmailBody = {
  email: string;
  firmId: string;
  samplePermission?: "admin" | "manager" | "editor" | "viewer";
  firmPermission?: "admin" | "manager" | "editor" | "viewer";
};
